# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0;/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/nix/store/c3bm9h7k398cmg00d4rss6hcxkl2zbl2-cmake-4.4.2/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "FMT built using CMake")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build;FMT;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/nikituch/Projects/nix-src/work/12.2.0/install")
set(CPACK_MODULE_PATH "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/support/cmake")
set(CPACK_NSIS_DISPLAY_NAME "fmt 12.2.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "fmt 12.2.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/nix/store/z4c6k0mrlkwl3s4w9ysxc8vq1wylm3ms-gcc-wrapper-15.3.0/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/nix/store/z4c6k0mrlkwl3s4w9ysxc8vq1wylm3ms-gcc-wrapper-15.3.0/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/nix/store/c3bm9h7k398cmg00d4rss6hcxkl2zbl2-cmake-4.4.2/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "FMT built using CMake")
set(CPACK_PACKAGE_FILE_NAME "fmt-12.2.0-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "fmt 12.2.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fmt 12.2.0")
set(CPACK_PACKAGE_NAME "fmt")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "12.2.0")
set(CPACK_PACKAGE_VERSION_MAJOR "12")
set(CPACK_PACKAGE_VERSION_MINOR "2")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/nix/store/z4c6k0mrlkwl3s4w9ysxc8vq1wylm3ms-gcc-wrapper-15.3.0/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/nix/store/c3bm9h7k398cmg00d4rss6hcxkl2zbl2-cmake-4.4.2/share/cmake-4.4/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/nix/store/c3bm9h7k398cmg00d4rss6hcxkl2zbl2-cmake-4.4.2/share/cmake-4.4/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "ZIP")
set(CPACK_SOURCE_IGNORE_FILES ".*[.]a$;.*[.]a/;.*[.]so.*$;.*[.]so.*/;.*[.]xcodeproj$;.*[.]xcodeproj/;.*~$;.*~/;.*[.]gradle/$;.*[.]gradle//;[.]vscode/$;[.]vscode//;[.]cache/$;[.]cache//;[.]vs/$;[.]vs//;/CMakeScripts$;/CMakeScripts/;/Testing$;/Testing/;/_CPack_Packages$;/_CPack_Packages/;/install_manifest[.]txt$;/install_manifest[.]txt/;CMakeCache[.]txt$;CMakeCache[.]txt/;CMakeUserPresets[.]json$;CMakeUserPresets[.]json/;CMakeFiles$;CMakeFiles/;CPack.*[.]cmake$;CPack.*[.]cmake/;CTestTestfile[.]cmake$;CTestTestfile[.]cmake/;FMT[.]build$;FMT[.]build/;Makefile$;Makefile/;bin/$;bin//;build/$;build//;cmake_install[.]cmake$;cmake_install[.]cmake/;fmt-.*[.]cmake$;fmt-.*[.]cmake/;fmt[.]pc$;fmt[.]pc/;/.git;/build($|/);.vagrant")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "fmt-12.2.0")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
