/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install"
#define EXEC_PREFIX "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install"
#define BINDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/bin"
#define SBINDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/sbin"
#define LIBEXECDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/libexec"
#define DATAROOTDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share"
#define DATADIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share"
#define SYSCONFDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/etc"
#define SHAREDSTATEDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/com"
#define LOCALSTATEDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/var"
#define RUNSTATEDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/var/run"
#define INCLUDEDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/doc/hello"
#define INFODIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/info"
#define HTMLDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/doc/hello"
#define DVIDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/doc/hello"
#define PDFDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/doc/hello"
#define PSDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/doc/hello"
#define LIBDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/lib"
#define LISPDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/emacs/site-lisp"
#define LOCALEDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/locale"
#define MANDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/man"
#define PKGDATADIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/share/hello"
#define PKGINCLUDEDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/include/hello"
#define PKGLIBDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/lib/hello"
#define PKGLIBEXECDIR "/home/nikituch/Projects/nix-src/work/hello-2.12.1/install/libexec/hello"
