# CMake generated Testfile for 
# Source directory: /home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test
# Build directory: /home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("args-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/args-test")
set_tests_properties("args-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;43;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("base-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/base-test")
set_tests_properties("base-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;44;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("assert-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/assert-test")
set_tests_properties("assert-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;45;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("chrono-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/chrono-test")
set_tests_properties("chrono-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;46;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("color-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/color-test")
set_tests_properties("color-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;47;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("gtest-extra-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/gtest-extra-test")
set_tests_properties("gtest-extra-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;48;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("format-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/format-test")
set_tests_properties("format-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;49;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("format-impl-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/format-impl-test")
set_tests_properties("format-impl-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;54;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("ostream-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/ostream-test")
set_tests_properties("ostream-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;56;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("compile-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/compile-test")
set_tests_properties("compile-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;57;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("printf-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/printf-test")
set_tests_properties("printf-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;58;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("ranges-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/ranges-test")
set_tests_properties("ranges-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;59;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("no-builtin-types-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/no-builtin-types-test")
set_tests_properties("no-builtin-types-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;60;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("scan-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/scan-test")
set_tests_properties("scan-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;61;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("std-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/std-test")
set_tests_properties("std-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;62;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("unicode-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/unicode-test")
set_tests_properties("unicode-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;71;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("xchar-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/xchar-test")
set_tests_properties("xchar-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;75;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("enforce-checks-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/enforce-checks-test")
set_tests_properties("enforce-checks-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;76;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("posix-mock-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/posix-mock-test")
set_tests_properties("posix-mock-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;110;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("os-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/os-test")
set_tests_properties("os-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;40;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;111;add_fmt_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
add_test("c-test" "/home/nikituch/Projects/nix-src/work/12.2.0/cmake-build/bin/c-test")
set_tests_properties("c-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;247;add_test;/home/nikituch/Projects/nix-src/work/12.2.0/fmt-12.2.0/test/CMakeLists.txt;0;")
subdirs("gtest")
